package com.soundrecovery.app;

import android.Manifest;import android.app.*;import android.os.*;import android.provider.MediaStore;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import android.media.MediaPlayer;import android.provider.Settings;import java.util.*;import java.io.*;

public class MainActivity extends Activity {
 LinearLayout box; TextView status; final int REQ=7, TREE=8; MediaPlayer player; ArrayList<Uri> uris=new ArrayList<>();
 @Override public void onCreate(Bundle b){super.onCreate(b);build();request();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(25,25,25));v.setPadding(0,12,0,12);return v;}
 void build(){ScrollView sv=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(32,45,32,45);sv.addView(box);box.addView(t("مستكشف التسجيلات العميق",25));box.addView(t("يفحص الصوتيات المتاحة ويتيح تشغيلها فورًا. اختر التخزين الداخلي للفحص اليدوي الأعمق للمجلدات التي يسمح بها أندرويد.",15));Button a=new Button(this);a.setText("فحص الصوتيات");a.setOnClickListener(v->scanMedia());box.addView(a);Button d=new Button(this);d.setText("اختيار مجلد وفحصه بعمق");d.setOnClickListener(v->openTree());box.addView(d);status=t("جاهز",15);box.addView(status);setContentView(sv);}
 void request(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.READ_MEDIA_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_AUDIO},REQ);else if(Build.VERSION.SDK_INT<33&&checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE},REQ);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ)scanMedia();}
 void clear(){while(box.getChildCount()>5)box.removeViewAt(5);uris.clear();}
 void scanMedia(){clear();status.setText("جاري فحص MediaStore…");new Thread(()->{ArrayList<String> names=new ArrayList<>();ArrayList<Uri> found=new ArrayList<>();String[] pr={MediaStore.Audio.Media._ID,MediaStore.Audio.Media.DISPLAY_NAME,MediaStore.Audio.Media.SIZE,MediaStore.Audio.Media.RELATIVE_PATH};try(Cursor c=getContentResolver().query(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,pr,null,null,MediaStore.Audio.Media.DATE_MODIFIED+" DESC")){if(c!=null)while(c.moveToNext()){long id=c.getLong(0);String n=c.getString(1),p=c.getString(3);if(n==null)continue;String x=n.toLowerCase();if(x.matches(".*\\.(aac|amr|m4a|mp3|wav|3gp|ogg|opus)$")||(p!=null&&p.toLowerCase().contains("soundrecorder"))){found.add(Uri.withAppendedPath(MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,""+id));names.add(n+"\n"+(p==null?"":p)+"\n"+(c.getLong(2)/1024)+" KB");}}}catch(Exception e){names.add("خطأ: "+e.getMessage());found.add(null);}runOnUiThread(()->show(names,found));}).start();}
 void openTree(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,TREE);}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==TREE&&c==RESULT_OK&&data!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}clear();status.setText("جاري الفحص العميق…");new Thread(()->{ArrayList<String> n=new ArrayList<>();ArrayList<Uri> f=new ArrayList<>();walk(u,n,f,0);runOnUiThread(()->show(n,f));}).start();}}
 void walk(Uri tree,ArrayList<String> n,ArrayList<Uri> f,int depth){if(depth>25)return;android.provider.DocumentsContract.buildChildDocumentsUriUsingTree(tree,android.provider.DocumentsContract.getTreeDocumentId(tree));Uri ch=android.provider.DocumentsContract.buildChildDocumentsUriUsingTree(tree,android.provider.DocumentsContract.getDocumentId(tree));try(Cursor c=getContentResolver().query(ch,new String[]{android.provider.DocumentsContract.Document.COLUMN_DOCUMENT_ID,android.provider.DocumentsContract.Document.COLUMN_DISPLAY_NAME,android.provider.DocumentsContract.Document.COLUMN_MIME_TYPE,android.provider.DocumentsContract.Document.COLUMN_SIZE},null,null,null)){if(c==null)return;while(c.moveToNext()){String id=c.getString(0),name=c.getString(1),mime=c.getString(2);Uri doc=android.provider.DocumentsContract.buildDocumentUriUsingTree(tree,id);if(android.provider.DocumentsContract.Document.MIME_TYPE_DIR.equals(mime))walk(doc,n,f,depth+1);else if(name!=null&&(name.toLowerCase().matches(".*\\.(aac|amr|m4a|mp3|wav|3gp|ogg|opus)$")||(mime!=null&&mime.startsWith("audio/")))){n.add(name+"\n"+(c.getLong(3)/1024)+" KB");f.add(doc);}}}catch(Exception ignored){}}
 void show(ArrayList<String> names,ArrayList<Uri> found){uris.addAll(found);status.setText("تم العثور على "+found.size()+" ملف — اضغط أي ملف لتشغيله");for(int i=0;i<names.size();i++){final int k=i;Button b=new Button(this);b.setAllCaps(false);b.setText(names.get(i)+"\n▶ تشغيل");b.setOnClickListener(v->play(k));box.addView(b);}}
 void play(int k){if(k>=uris.size()||uris.get(k)==null)return;try{if(player!=null){player.stop();player.release();}player=new MediaPlayer();player.setDataSource(this,uris.get(k));player.setOnPreparedListener(MediaPlayer::start);player.setOnCompletionListener(mp->status.setText("انتهى التشغيل"));player.prepareAsync();status.setText("جاري تشغيل الملف…");}catch(Exception e){status.setText("تعذر تشغيله: "+e.getMessage());}}
 @Override protected void onDestroy(){if(player!=null)player.release();super.onDestroy();}
}